import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import "../public/css/bootstrap.min.css";
import "../public/css/chat-tool.css";
import "@/public/css/icon.css";
import "../public/css/ionicons.min.css";
import "../public/css/lightbox.css";
import "../public/css/owl.carousel.min.css";
import "../public/css/owl.theme.default.min.css";
import "../public/css/slick-theme.css";
import "../public/css/slick.css";
import "../public/css/style.css";
import "font-awesome/css/font-awesome.min.css";
import Header from "@/components/shared/Header";
import { TopArea } from "@/components/shared/TopArea";
import Footer from "@/components/shared/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <TopArea />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
